Task3 from homework6
foiki/spbu-Homeworks pull request #14
Opened 2018-11-07 17:26 UTC by foiki

2018-11-17 06:55 UTC, jzuken requested changes

2018-11-17 06:55 UTC, jzuken commented on sem1/homework6/task3/main.cpp
> +    int *array = new int[number];
:(

2018-11-17 06:55 UTC, jzuken commented on sem1/homework6/task3/main.cpp
> +int main()
Enter the number of coefficients:
1
Enter the coefficients:
-1

-x

а свободный член где?

2018-11-17 06:55 UTC, jzuken commented on sem1/homework6/task3/main.cpp
> +void outputDegrees (int array[], int number)
пробел лишниий

2018-11-17 06:55 UTC, jzuken commented on sem1/homework6/task3/main.cpp
> +            } else
перенос строки

2018-11-24 16:47 UTC, jzuken commented
теперь пример из условия отражается некорректно

2018-11-24 18:31 UTC, foiki commented
@jzuken Ответ же вроде совпадает с тем, что в условии

Enter the number of coefficients: 
14
Enter the coefficients: 
-1 12321 0 0 0 -1 -1 -1 1 1 34 -2 0 0

  13        12   8   7   6   5   4     3    2
-x  + 12321x  - x - x - x + x + x + 34x - 2x

Program ended with exit code: 0

2018-11-24 18:43 UTC, jzuken commented
попробуй ввести 13 как число коэффициентов, а потом -1 12321 0 0 0 -1 -1 -1 1 1 34 -2 0

2018-12-04 11:21 UTC, merged