Task1 from homework7
foiki/spbu-Homeworks pull request #16
Opened 2018-11-12 17:36 UTC by foiki

2018-11-18 16:11 UTC, ujohnny requested changes

2018-11-18 16:11 UTC, ujohnny commented on sem1/homework7/task1/ATDSet.cpp
> +#include "ATDSet.h"
ну тогда ADT

2018-11-18 16:11 UTC, ujohnny commented on sem1/homework7/task1/main.cpp
> +    int newRequest = -1;
и если вы воспользуетесь do...while, то у вас эта переменная уедет в нормальный скоуп жизнь

2018-11-18 16:11 UTC, ujohnny commented on sem1/homework7/task1/main.cpp
> +#include "ATDSet.h"
вам здесь определенно BinaryTree не нужно. BinaryTree это по сути implementation details вашего  Set. и почему у вас везде внизу binarytree вместо seet это очень хороший вопрос

2018-11-24 18:47 UTC, jzuken requested changes

2018-11-24 18:47 UTC, jzuken commented on sem1/homework7/task1/ATD.cpp
> +#include "ATD.h"
что за atd? это всё равно, что назвать файл "тип данных", тут конкретное имя типа должно быть.
и да, всё ещё не видно множества тут

2018-12-06 10:52 UTC, jzuken requested changes

2018-12-06 10:52 UTC, jzuken commented on sem1/homework7/task1/ATDSet.cpp
> +    delete[] set;
:(

2018-12-18 07:18 UTC, merged