Task1 from homework6
foiki/spbu-Homeworks pull request #17
Opened 2018-11-14 18:48 UTC by foiki

2018-11-20 10:48 UTC, jzuken commented on sem1/homework6/task1/main.cpp
> +        numberInBinary[6] &= 0b00001111;
а зачем все эти операции, если numberInBinary никто не использует дальше?

2018-11-21 17:51 UTC, foiki commented on sem1/homework6/task1/main.cpp
> +        numberInBinary[6] &= 0b00001111;
> а зачем все эти операции, если numberInBinary никто не использует дальше?

numberInBinary создается по ссылке на number, а number дальше используется

2018-11-22 12:35 UTC, jzuken commented on sem1/homework6/task1/main.cpp
> +        numberInBinary[6] &= 0b00001111;
ну вот такой чудесный у тебя код, что смотришь на него и сходу непонятно. выглядит всё как магия с волшебными константами

2018-11-24 12:24 UTC, foiki commented on sem1/homework6/task1/main.cpp
> +        numberInBinary[6] &= 0b00001111;
> ну вот такой чудесный у тебя код, что смотришь на него и сходу непонятно. выглядит всё как магия с волшебными константами

добавил функции для вычисления мантиссы и порядка

2018-12-04 11:16 UTC, jzuken requested changes

2018-12-04 11:16 UTC, jzuken commented on sem1/homework6/task1/main.cpp
> +int degreeCalculating(unsigned char *numberInBinary)
ещё раз: имя функции лучше всего строить на основе глагола. функция -- это некоторое действие, а не процесс, как у тебя тут

2018-12-17 14:15 UTC, merged