Task2 from homework9
foiki/spbu-Homeworks pull request #26
Opened 2018-12-07 10:40 UTC by foiki

2018-12-17 16:20 UTC, ujohnny requested changes

2018-12-17 16:20 UTC, ujohnny commented on sem1/homework9/task2/main.cpp
> +    textRead(symbols, numberOfEachSymbol, text, numberOfSymbols);
что значит textRead? как из названия ф-и понять ее контракт?

2018-12-17 16:20 UTC, ujohnny commented on sem1/homework9/task2/main.cpp
> +    huffmanAlgorithm(huffmanTree, symbols, numberOfEachSymbol, numberOfSymbols);
что значит huffmanAlgorithm, как понять что тут будет сделано?

2018-12-17 16:20 UTC, ujohnny commented on sem1/homework9/task2/main.cpp
> +    int *numberOfEachSymbol = new int[size]{0};
возможно это стоит назвать symbolFrequency ?

2018-12-18 07:30 UTC, jzuken commented
huffman.cpp: In function ‘void findSymbolFrequencyInText(char*, int*, char*, int&)’:
huffman.cpp:10:30: error: ‘strlen’ was not declared in this scope
     long length = strlen(text);
                              ^
huffman.cpp: In function ‘void buildAHuffmanTree(HuffmanTree*, char*, int*, int)’:
huffman.cpp:36:96: error: could not convert ‘{charToString(newElement), (*(symbolFrequency + ((sizetype)(((long unsigned int)i) * 4ul)))), nullptr, nullptr}’ from ‘<brace-enclosed initializer list>’ to ‘Node’
         Node *newNode = new Node{charToString(newElement), symbolFrequency[i], nullptr, nullptr};
                                                                                                ^
huffman.cpp: In function ‘void printCode(String**, char*)’:
huffman.cpp:95:30: error: ‘strlen’ was not declared in this scope
     long length = strlen(text);

2018-12-21 12:08 UTC, jzuken commented
тут всё очень плохо с очисткой памяти

2018-12-21 14:51 UTC, jzuken commented
закодировал
```
beep boop beer!
asdas,asdsad.....

a,,a
d
```
раскодировал, получил 
```
s

ass
assaa..p
boop beer!
asdas,asdsad.....

a,,a
d
```

2018-12-22 16:21 UTC, jzuken commented
==2292== 352 bytes in 11 blocks are indirectly lost in loss record 98 of 101
==2292==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2292==    by 0x401378: buildAHuffmanTree(HuffmanTree*, char*, int*, int) (huffman.cpp:51)
==2292==    by 0x401D51: main (main.cpp:19)
==2292==
==2292== 416 bytes in 13 blocks are indirectly lost in loss record 99 of 101
==2292==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2292==    by 0x401298: buildAHuffmanTree(HuffmanTree*, char*, int*, int) (huffman.cpp:40)
==2292==    by 0x401D51: main (main.cpp:19)
==2292==
==2292== 800 (32 direct, 768 indirect) bytes in 1 blocks are definitely lost in loss record 100 of 101
==2292==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2292==    by 0x4013F0: buildAHuffmanTree(HuffmanTree*, char*, int*, int) (huffman.cpp:57)

2018-12-24 08:51 UTC, jzuken commented
> На выходе текстовый файл, состоящих из двух строк.

обидно из-за этого зачёт не получить, да?

2018-12-24 09:00 UTC, merged