Task2 from homework10
foiki/spbu-Homeworks pull request #30
Opened 2018-12-13 20:08 UTC by foiki

2018-12-19 14:47 UTC, ujohnny requested changes

2018-12-19 14:47 UTC, ujohnny commented on sem1/homework10/task2/rabinKarpAlgorithm.cpp
> +int hashFunction(string line)
оно у вас очень легко может не поместиться в int

2018-12-19 14:47 UTC, ujohnny commented on sem1/homework10/task2/rabinKarpAlgorithm.cpp
> +        result = ((result + line.c_str()[i]) * prime);
а зачем `c_str()` ?

2018-12-19 14:47 UTC, ujohnny commented on sem1/homework10/task2/rabinKarpAlgorithm.cpp
> +        long newSubLineHash = hashFunction(newSubLine);
это совсем не алгоритм рабина-карпа. он сначала считает хэши префиксов, а потом вычисляет хэши подстрок просто операцией `-`

2018-12-19 15:54 UTC, foiki commented on sem1/homework10/task2/rabinKarpAlgorithm.cpp
> +int hashFunction(string line)
@ujohnny long long думаю не сильно улучшит ситуацию, добавить взятие по модулю?

2018-12-19 16:25 UTC, foiki commented on sem1/homework10/task2/rabinKarpAlgorithm.cpp
> +        long newSubLineHash = hashFunction(newSubLine);
@ujohnny мы разбирали, что нужно сначала сравнить хеши подстрок, в случае если они равны, сравнить посимвольно уже

2018-12-19 18:08 UTC, jzuken commented on sem1/homework10/task2/rabinKarpAlgorithm.cpp
> +        long newSubLineHash = hashFunction(newSubLine);
так смысл алгоритма в том, что хеши пересчитываются не с нуля, а на основе предыдущего хеша

2018-12-21 14:16 UTC, jzuken requested changes

2018-12-21 14:16 UTC, jzuken commented on sem1/homework10/task2/main.cpp
> +    string line = "";
у нас как бы нельзя библиотечный string использовать, весь семестр про это говорю

2018-12-22 15:33 UTC, jzuken requested changes

2018-12-22 15:33 UTC, jzuken commented on sem1/homework10/task2/rabinKarpAlgorithm.cpp
> +            newSubLine = subLineCopy(newSubLine, string, 0, secondLength);
не надо тут ничего копировать, это же дико долго. весь смысл инкрементального пересчёта хешей теряется

2018-12-23 14:17 UTC, jzuken requested changes

2018-12-23 14:17 UTC, jzuken commented on sem1/homework10/task2/rabinKarpAlgorithm.cpp
> +            newSubLine = subLineCopy(newSubLine, string, i, secondLength);
то есть ты считаешь, что посимвольное копирование и подсчёт хеша быстрее, чем посимвольное сравнение? :)

2018-12-24 09:01 UTC, merged