Task1 from homework10
foiki/spbu-Homeworks pull request #35
Opened 2018-12-18 19:36 UTC by foiki

2018-12-21 14:15 UTC, jzuken requested changes

2018-12-21 14:15 UTC, jzuken commented on sem1/homework10/task1/graph.cpp
> +    checkNewPoint(graph, queue, used, current->x - 1, current->y);
ну как-то здесь тоже память утекает

2018-12-21 14:15 UTC, jzuken commented on sem1/homework10/task1/graph.hpp
> +void deleteIntMatrix(int **matrix, int size);
эти функции точно все должны быть частью интерфейса модуля работы  с графом?

2018-12-21 17:37 UTC, foiki commented on sem1/homework10/task1/graph.cpp
> +    checkNewPoint(graph, queue, used, current->x - 1, current->y);
@jzuken но там же вызывается 4 раза одна и та же функция, которая добавляет элемент в очередь, если его там нет, либо же удаляет и память вроде как чистится

2018-12-22 19:45 UTC, jzuken commented on sem1/homework10/task1/graph.cpp
> +    checkNewPoint(graph, queue, used, current->x - 1, current->y);
профилировщик не ошибается

2018-12-22 19:48 UTC, foiki commented on sem1/homework10/task1/graph.cpp
> +    checkNewPoint(graph, queue, used, current->x - 1, current->y);
@jzuken Он может на это ругаться: "Node *newNode = new Node {x, y};"?

2018-12-22 19:49 UTC, foiki commented on sem1/homework10/task1/graph.cpp
> +    checkNewPoint(graph, queue, used, current->x - 1, current->y);
@jzuken на то, что я объявляю в фигурных скобках

2018-12-24 08:54 UTC, jzuken commented on sem1/homework10/task1/graph.cpp
> +    checkNewPoint(graph, queue, used, current->x - 1, current->y);
да нет, в этом случае он работу с памятью проверяет

2018-12-24 08:59 UTC, jzuken requested changes

2018-12-24 08:59 UTC, jzuken commented on sem1/homework10/task1/aStar.cpp
> +    Node *current = new Node {end->x, end->y};
этого тоже никто не удалил

2018-12-24 08:59 UTC, jzuken commented on sem1/homework10/task1/aStar.cpp
> +        delete current;
а этот походу два раза удаляется, тут и потом при очистке очереди

2018-12-24 09:08 UTC, foiki commented on sem1/homework10/task1/aStar.cpp
> +    Node *current = new Node {end->x, end->y};
@jzuken странно, профилятор не ругался по памяти

2018-12-24 09:13 UTC, foiki commented on sem1/homework10/task1/aStar.cpp
> +    Node *current = new Node {end->x, end->y};
@jzuken я его пытался удалить, помле удаления очереди, но выдавало ошибку, что памяти под него не выделено, я убрал, все стало нормально, и по памяти не было ошибок

2018-12-24 09:16 UTC, jzuken commented
==12371== Invalid free() / delete / delete[] / realloc()
==12371==    at 0x4C2F24B: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12371==    by 0x40238B: deleteQueue(Queue*) (queue.cpp:14)
==12371==    by 0x401833: aStar(Graph*, Node*, Node*) (aStar.cpp:124)
==12371==    by 0x401E4D: main (main.cpp:22)
==12371==  Address 0x5ac0530 is 0 bytes inside a block of size 8 free'd
==12371==    at 0x4C2F24B: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12371==    by 0x401637: aStar(Graph*, Node*, Node*) (aStar.cpp:104)
==12371==    by 0x401E4D: main (main.cpp:22)
==12371==  Block was alloc'd at
==12371==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12371==    by 0x4012E8: checkNewPoint(Graph*, Queue*, bool**, int, int) (aStar.cpp:54)
==12371==    by 0x4013C7: addNeighboursToQueue(Graph*, Queue*, bool**, Node*) (aStar.cpp:70)
==12371==    by 0x401626: aStar(Graph*, Node*, Node*) (aStar.cpp:102)
==12371==    by 0x401E4D: main (main.cpp:22)
==12371==
==12371==
==12371== HEAP SUMMARY:
==12371==     in use at exit: 72,712 bytes in 2 blocks
==12371==   total heap usage: 361 allocs, 360 frees, 87,784 bytes allocated
==12371==
==12371== 8 bytes in 1 blocks are definitely lost in loss record 1 of 2
==12371==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12371==    by 0x4016C4: aStar(Graph*, Node*, Node*) (aStar.cpp:112)
==12371==    by 0x401E4D: main (main.cpp:22)

2018-12-24 09:16 UTC, jzuken commented
не знаю. 8 bytes in 1 blocks are definitely lost. причём показывает в твой код

2018-12-24 12:30 UTC, foiki commented on sem1/homework10/task1/aStar.cpp
> +        delete current;
@jzuken мы делаем remove из очереди для этого элемента, а потом удаляем сам этот элемент, в очереди он потом не содержится

2018-12-27 10:51 UTC, merged