Added task1 from homework2
foiki/spbu-Homeworks pull request #39
Opened 2019-02-27 18:51 UTC by foiki

2019-03-08 20:08 UTC, PrikhodkoStanislav requested changes

2019-03-08 20:08 UTC, PrikhodkoStanislav commented on sem2/homework2/task1/src/main/java/group144/kireev/QuickSort.java
> +        {
Проверяй стайлгайд! В Java открывающая фигурная скобка остается на предыдущей строке.

2019-03-11 09:37 UTC, jzuken requested changes

2019-03-11 09:37 UTC, jzuken commented on sem2/homework2/task1/src/main/java/group144/kireev/BubbleSort.java
> +public class BubbleSort implements Sorter {
джавадоки где?

2019-03-11 09:37 UTC, jzuken commented on sem2/homework2/task1/src/test/java/group144/kireev/BubbleSortTests.java
> +import org.junit.Test;
лучше использовать JUnit 5

2019-04-10 12:56 UTC, merged