Added task2 from homework2
foiki/spbu-Homeworks pull request #41
Opened 2019-03-09 23:16 UTC by foiki

2019-03-19 09:11 UTC, ujohnny commented on sem2/homework2/task2/src/main/java/group144/kireev/Calculator.java
> +    public int calculate(String string) throws WrongExpressionException {
а чтобы ее тогда статической не сделать, ведь вам никакое состояние не нужно.

2019-03-19 09:12 UTC, ujohnny commented on sem2/homework2/task2/src/main/java/group144/kireev/ArrayStack.java
> +            throw new NullPointerException("Nothing to delete!");
это misuse типа исключения.

2019-03-19 09:12 UTC, ujohnny commented on sem2/homework2/task2/src/main/java/group144/kireev/ArrayStack.java
> +            throw new NullPointerException("Nothing to delete!");
и здесь тоже misuse

2019-03-19 09:19 UTC, foiki commented on sem2/homework2/task2/src/main/java/group144/kireev/ArrayStack.java
> +            throw new NullPointerException("Nothing to delete!");
@ujohnny нужно создать свой класс для этого исключения?

2019-03-19 09:26 UTC, ujohnny commented on sem2/homework2/task2/src/main/java/group144/kireev/Stack.java
> +    int pop() throws NullPointerException;
тут тоже misuse, и почему print его кидает? если для pop еще можно сделать EmptyStackException, то для print то что?

2019-03-19 09:31 UTC, ujohnny commented on sem2/homework2/task2/src/main/java/group144/kireev/Calculator.java
> +        switch (operation) {
вообще бы operation превратить в enum

2019-03-19 09:31 UTC, ujohnny commented on sem2/homework2/task2/src/main/java/group144/kireev/Calculator.java
> +    /** Method that checks whether the Ыекштп object is a number*/
Ыекштп ???

2019-03-19 09:32 UTC, ujohnny commented on sem2/homework2/task2/src/main/java/group144/kireev/Calculator.java
> +    /** Method that reads two numbers and a sign of the operation and returns the result of this operation on the read numbers*/
тут больше 120 символов в строчке

2019-03-19 09:51 UTC, ujohnny commented on sem2/homework2/task2/src/main/java/group144/kireev/ArrayStack.java
> +            throw new NullPointerException("Nothing to delete!");
@foiki можете этим вдохновиться https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Stack.html#pop()

2019-03-21 21:13 UTC, ujohnny commented on sem2/homework2/task2/src/main/java/group144/kireev/Calculator.java
> +        switch (operation) {
а что насчет этого?

2019-03-21 21:14 UTC, ujohnny commented
а в этой задаче вам надо реализовать только целочисленные операции или с числами с плавающей точкой тоже?

2019-03-21 21:16 UTC, ujohnny commented on sem2/homework2/task2/src/main/java/group144/kireev/Calculator.java
> +    public static int operations (int firstOperand, int secondOperand, String operation) throws WrongExpressionException {
использование множественного числа сущетсвительного для названия ф-и довольно странное решение, назовите ее нормально

2019-03-21 21:17 UTC, ujohnny commented on sem2/homework2/task2/src/test/java/group144/kireev/LinkedStackTest.java
> +        assertEquals(true, stack.isEmpty());
правильно использовать ф-и `assertTrue`/`assertFalse`

2019-03-21 21:22 UTC, ujohnny commented on sem2/homework2/task2/src/test/java/group144/kireev/LinkedStackTest.java
> +        Stack stack = new LinkedStack();
можете посмотреть на ф-ю setup/teardown, там есть варианты для каждого теста и для сьюта в целом

2019-03-21 21:23 UTC, ujohnny commented on sem2/homework2/task2/src/test/java/group144/kireev/CalculatorTest.java
> +        } catch (WrongExpressionException e) {}
вот здесь у вас может быть проблема, если кто-то сломает код и он будет кидать эксепшн, то тест будет проходить. возможно вам стоит убрать отсюда `try/catch` и добавить throws в сигнатуру ф-и

2019-03-22 10:31 UTC, foiki commented
@ujohnny про числа с плавающей точкой не говорили в задаче

2019-03-22 14:45 UTC, ujohnny commented on sem2/homework2/task2/src/main/java/group144/kireev/Calculator.java
> +    public static int operations (int firstOperand, int secondOperand, String operation) throws WrongExpressionException {
На самом деле я имел ввиду, что неплохо бы добавить глагол. К примеру `performOperation`

2019-03-22 14:46 UTC, ujohnny commented on sem2/homework2/task2/src/test/java/group144/kireev/LinkedStackTest.java
> +        Stack stack = new LinkedStack();
А здесь хотел сказать, что создание стэка вы можете перенести в setup/teardown

2019-03-22 16:38 UTC, foiki commented on sem2/homework2/task2/src/test/java/group144/kireev/LinkedStackTest.java
> +        Stack stack = new LinkedStack();
@ujohnny нашел эти методы для  JUnit 4, нам сказали использовать JUnit 5

2019-04-13 18:26 UTC, ujohnny approved these changes

2019-04-29 07:29 UTC, jzuken requested changes

2019-04-29 07:29 UTC, jzuken commented on sem2/homework2/task2/src/main/java/group144/kireev/ArrayStack.java
> +        ++length;
а чего оно переполнение никак не проверяет?

2019-04-29 07:29 UTC, jzuken commented on sem2/homework2/task2/src/main/java/group144/kireev/EmptyStackException.java
> +public class EmptyStackException extends Exception {
к исключениям тоже надо писать доки

2019-04-29 07:29 UTC, jzuken commented on sem2/homework2/task2/src/main/java/group144/kireev/Stack.java
> +public interface Stack {
доки?

2019-04-29 07:29 UTC, jzuken commented on sem2/homework2/task2/src/test/java/group144/kireev/LinkedStackTest.java
> +        Stack stack = new LinkedStack();
и что? в пятом это делается аннотациями Before и т.п.

2019-05-11 10:58 UTC, merged