Added task2 from homework3
foiki/spbu-Homeworks pull request #42
Opened 2019-03-18 17:59 UTC by foiki

2019-04-13 18:52 UTC, ujohnny commented on sem2/homework3/task2/src/main/java/group144/kireev/OperatorNode.java
> +    OperatorNode(Scanner in) throws WrongExpressionException {
у вас код, который парсит и создает узлы как то слился и распределился по этим двум конструкторам. не мешайте все это в кучу, распарсите в одном месте, и создадите более простые конструкторы для этих узлом

2019-04-13 19:30 UTC, ujohnny commented on sem2/homework3/task2/src/main/java/group144/kireev/OperandNode.java
> +        if (operandAndBracket.charAt(bracketIndex) == ')') {
"Можно считать, что входной файл корректен"
на самом деле это подсказка, что все `(` и `)` можно игнорировать

2019-04-20 17:14 UTC, foiki commented on sem2/homework3/task2/src/main/java/group144/kireev/OperandNode.java
> +        if (operandAndBracket.charAt(bracketIndex) == ')') {
@ujohnny это условие проверяет первое число в операции считано или второе, чтобы скобку отделить от второго

2019-04-21 13:27 UTC, foiki commented on sem2/homework3/task2/src/main/java/group144/kireev/OperatorNode.java
> +    OperatorNode(Scanner in) throws WrongExpressionException {
@ujohny, не совсем представляю убрать сканер из конструктора, если дальше дерево строится рекурсивно

2019-05-02 08:37 UTC, jzuken requested changes

2019-05-02 08:37 UTC, jzuken commented on sem2/homework3/task2/src/main/java/group144/kireev/ExpressionTree.java
> +public class ExpressionTree {
доки?

2019-05-11 11:10 UTC, merged