Task1 from homework3
foiki/spbu-Homeworks pull request #43
Opened 2019-03-24 11:13 UTC by foiki

2019-04-13 18:40 UTC, ujohnny requested changes

2019-04-13 18:40 UTC, ujohnny commented on sem2/homework3/task1/src/main/java/group144/kireev/Main.java
> +        String element;
а это тут зачем затесалось, его поближе к месту использования никак нельзя подвинуть?

2019-04-13 18:40 UTC, ujohnny commented on sem2/homework3/task1/src/main/java/group144/kireev/HashTable.java
> +    private HashFunction hashFunction;
а где "Смена хэш-функции должна происходить во время работы программы" ? 
а где разрастрание хэш таблицы при превышение лоад фактор и полный рехэшинг?

2019-05-03 16:00 UTC, jzuken requested changes

2019-05-03 16:00 UTC, jzuken commented on sem2/homework3/task1/src/main/java/group144/kireev/HashFunction.java
> +/** Interface realizes HashFunction */
чего? интерфейс реализует сам себя?

2019-05-03 16:00 UTC, jzuken commented on sem2/homework3/task1/src/main/java/group144/kireev/HashFunction.java
> +/** Interface realizes HashFunction */
а доки к методам где?

2019-05-03 16:00 UTC, jzuken commented on sem2/homework3/task1/src/main/java/group144/kireev/HashFunction.java
> +    int getMod();
это тут не нужно, нужна просто функция, принимающая строку и возвращающая её хеш-код

2019-05-03 16:00 UTC, jzuken commented on sem2/homework3/task1/src/main/java/group144/kireev/HashTable.java
> +        return newHashTable;
непонятно, зачем она новую таблицу возвращает. у тебя же уже есть таблица, её и меняй

2019-05-03 16:00 UTC, jzuken commented on sem2/homework3/task1/src/main/java/group144/kireev/HashTable.java
> +        }
да, при достижении порогов load factor'а хорошо бы таблицу ресайзить

2019-05-03 16:00 UTC, jzuken commented on sem2/homework3/task1/src/main/java/group144/kireev/HashTable.java
> +    public int getNumberOfAddedWords() { return uniqueWordsAdded; }
не особо по стайлгайду

2019-05-03 20:55 UTC, foiki commented on sem2/homework3/task1/src/main/java/group144/kireev/HashTable.java
> +        return newHashTable;
@jzuken ну тогда получается нужно все элементы из таблицы удалить, сменить хэш-функцию и добавить их снова, мне кажется проще их добавить сразу в новую таблицу

2019-05-04 16:29 UTC, jzuken commented on sem2/homework3/task1/src/main/java/group144/kireev/HashTable.java
> +        return newHashTable;
разумеется, именно так и нужно сделать. ты выполняешь операцию над объектов, какого хрена он вдруг новый возвращает?

2019-05-11 14:58 UTC, jzuken requested changes

2019-05-11 14:58 UTC, jzuken commented on sem2/homework3/task1/src/main/java/group144/kireev/HashFunction.java
> +    int hash(String string);
а размер ему не нужен? в каком диапазоне оно будет хеши генерить?

2019-05-11 14:58 UTC, jzuken commented on sem2/homework3/task1/src/main/java/group144/kireev/HashTable.java
> +        if (!exist(element)) {
а можно инвертировать это условие и сразу выйти. и тогда код станет чище и понятнее

2019-05-11 14:58 UTC, jzuken commented on sem2/homework3/task1/src/main/java/group144/kireev/HashTable.java
> +        LinkedList<String> elements = getAllElements();
если ты не издеваешься и серьёзно думаешь, что это лучшее решение, то это весьма печально. ну то есть вместо того, чтобы локально сохранить копию на старый массив, создать новый и переложить туда все элементы, ты их по одному удаляешь сначала

2019-05-11 15:04 UTC, foiki commented on sem2/homework3/task1/src/main/java/group144/kireev/HashFunction.java
> +    int hash(String string);
@jzuken ну я тут просто считаю хэш, а уже при передаче в таблицу он берет остаток по текущему размеру

2019-06-06 08:55 UTC, merged