Task 1 from homework5
foiki/spbu-Homeworks pull request #47
Opened 2019-04-05 17:57 UTC by foiki

2019-04-15 14:40 UTC, ujohnny approved these changes

2019-05-04 17:35 UTC, jzuken requested changes

2019-05-04 17:35 UTC, jzuken commented on sem2/homework5/task1/out/production/resources/group144/kireev/Main.fxml
> +<?xml version="1.0" encoding="UTF-8"?>
зачем это тут?

2019-05-04 17:35 UTC, jzuken commented on sem2/homework5/task1/src/main/resources/group144/kireev/Main.fxml
> +<AnchorPane fx:controller="group144.kireev.Controller" maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="400.0" prefWidth="600.0" xmlns="http://javafx.
хотелось бы, чтобы окно зумилось и содержимое зумилось вместе с окном

2019-06-06 09:37 UTC, jzuken commented
а можно сделать так, чтобы вот такое нельзя было зазумить?

![2019-06-06 11_37_01-Slider and Progress Bar](https://user-images.githubusercontent.com/705678/59023177-7946fc80-884f-11e9-9463-678c4267a248.png)

2019-06-11 08:51 UTC, merged

2019-06-11 08:53 UTC, jzuken commented
это я зазумил на максимум:
![2019-06-11 11_53_04-Simple Calculator](https://user-images.githubusercontent.com/705678/59257882-809b4b00-8c3f-11e9-97c2-e7354545aaba.png)