Task2 from homework5
foiki/spbu-Homeworks pull request #48
Opened 2019-04-06 17:55 UTC by foiki

2019-04-15 14:42 UTC, ujohnny requested changes

2019-04-15 14:42 UTC, ujohnny commented on sem2/homework5/task2/src/main/java/group144/kireev/Controller.java
> +        SpinnerValueFactory<Integer> values = new SpinnerValueFactory.IntegerSpinnerValueFactory(-9, 9, 0);
эта переменная как то тут потерялась

2019-04-15 14:42 UTC, ujohnny commented on sem2/homework5/task2/src/main/java/group144/kireev/Controller.java
> +        firstValue.valueProperty().addListener((observable, oldValue, newValue) -> calculate());
может быть стоит лямбду один раз инстанциировать?

2019-05-04 17:42 UTC, jzuken requested changes

2019-05-04 17:42 UTC, jzuken commented on sem2/homework5/task2/src/main/java/group144/kireev/Controller.java
> +        SpinnerValueFactory<Integer> values = new SpinnerValueFactory.IntegerSpinnerValueFactory(-9, 9, 0);
угу

2019-05-04 17:42 UTC, jzuken commented on sem2/homework5/task2/src/main/java/group144/kireev/Controller.java
> +        firstValue.valueProperty().addListener((observable, oldValue, newValue) -> calculate());
однозначно стоит. а вот игнорировать замечания проверяющего не стоит

2019-05-04 17:42 UTC, jzuken commented on sem2/homework5/task2/src/main/java/group144/kireev/Controller.java
> +    private void calculate() {
вот в такой реализации часть с логикой приложения (подсчёт выражения) неотделима от части обработки UI. её же отдельно не протестировать даже никак. надо разделить их на две сущности

2019-05-04 17:42 UTC, jzuken commented on sem2/homework5/task2/src/main/resources/group144/kireev/Main.fxml
> +<AnchorPane prefHeight="367.0" prefWidth="600.0" xmlns="http://javafx.com/javafx/11.0.1" xmlns:fx="http://javafx.com/fxml/1" fx:controller="group144.kireev.Controller">
ну и зумом тут такое же замечание

2019-05-04 18:36 UTC, foiki commented on sem2/homework5/task2/src/main/java/group144/kireev/Controller.java
> +    private void calculate() {
@jzuken нужно ли делать тесты для такой простой реализации метода? Просто тогда надо будет сделать метод public

2019-05-05 05:53 UTC, jzuken commented on sem2/homework5/task2/src/main/java/group144/kireev/Controller.java
> +    private void calculate() {
ну так это уже другая сущность будет

2019-05-11 14:39 UTC, jzuken requested changes

2019-05-11 14:39 UTC, jzuken commented on sem2/homework5/task2/src/main/resources/group144/kireev/Main.fxml
> +<?import javafx.scene.layout.RowConstraints?>
хорошо бы минимальный размер ещё задать

2019-05-11 17:26 UTC, foiki commented on sem2/homework5/task2/src/main/resources/group144/kireev/Main.fxml
> +<?import javafx.scene.layout.RowConstraints?>
@jzuken минимальный размер рядов задать? У меня он вроде для всех указан

2019-06-06 09:39 UTC, jzuken commented
та же фигня с зумом

2019-06-11 11:05 UTC, merged