Task1 from homework4
foiki/spbu-Homeworks pull request #5
Opened 2018-10-14 14:39 UTC by foiki

2018-10-27 14:58 UTC, jzuken requested changes

2018-10-27 14:58 UTC, jzuken commented on sem1/homework4/task1/list.cpp
> +void connect(List *list, int number)
не, лучше сразу создавать список циклическим, а эта функция непонятно зачем

2018-10-27 14:58 UTC, jzuken commented on sem1/homework4/task1/main.cpp
> +        if (j % spot == 0 && current->killed)
это всё очень сложно. можно просто удалять убитых солдат из списка, и тогда не надо будет этих всех проверок

2018-10-27 14:58 UTC, jzuken commented on sem1/homework4/task1/main.cpp
> +    while(number - killedInThisCircle > 1)
пробел

2018-10-27 19:03 UTC, foiki commented on sem1/homework4/task1/main.cpp
> +        if (j % spot == 0 && current->killed)
@jzuken если ух удалять, то круг будет постоянно смещаться. Или удалять после очередного круга?

2018-11-02 12:31 UTC, jzuken commented on sem1/homework4/task1/main.cpp
> +        if (j % spot == 0 && current->killed)
я не понял вопроса. ты ходишь по кругу и удаляешь каждого n-го до тех пор, пока не останется один в этом круге. кто куда будет смещаться?

2018-11-02 12:32 UTC, jzuken requested changes

2018-11-02 12:32 UTC, jzuken commented on sem1/homework4/task1/warriors.h
> +#pragma once
опять же, git mv. не надо тут плодить лишних файлов

2018-11-06 13:22 UTC, merged