Task2 from homework4
foiki/spbu-Homeworks pull request #6
Opened 2018-10-17 18:31 UTC by foiki

2018-10-27 22:13 UTC, jzuken requested changes

2018-10-27 22:13 UTC, jzuken commented on sem1/homework4/task2/list.cpp
> +#include <iostream>
лучше сначала писать системные инклуды, а потом свои

2018-10-27 22:13 UTC, jzuken commented on sem1/homework4/task2/list.cpp
> +        if(!fin.eof())
пробел

2018-10-27 22:13 UTC, jzuken commented on sem1/homework4/task2/list.cpp
> +void assignment(char a[], char b[])
имя функции -- глагол

2018-10-27 22:13 UTC, jzuken commented on sem1/homework4/task2/list.cpp
> +bool charComparsion(char a[], char b[])
опять же имя плохо согласуется с возвращаемым типом

2018-10-27 22:13 UTC, jzuken commented on sem1/homework4/task2/list.cpp
> +void phoneNumberFinder(List *list, char a[])
и тут

2018-10-27 22:13 UTC, jzuken commented on sem1/homework4/task2/list.cpp
> +void firstRequest(List *list)
это всё равно что назвать функцию f1, ничего не говорит о её сути

2018-10-27 22:13 UTC, jzuken commented on sem1/homework4/task2/list.h
> +#pragma once
и почему файл называется list?

2018-10-27 22:13 UTC, jzuken commented on sem1/homework4/task2/list.h
> +#include <fstream>
это в заголовочном файле точно не надо

2018-10-27 22:13 UTC, jzuken commented on sem1/homework4/task2/main.cpp
> +        else
а если писать else if в одну строчку, то не будет этих противных отступов в таком количестве

2018-10-27 22:17 UTC, foiki commented on sem1/homework4/task2/list.h
> +#pragma once
@jzuken а по какому принципу надо называть заголовочные файлы?

2018-10-28 15:26 UTC, jzuken commented on sem1/homework4/task2/list.h
> +#pragma once
по принципу того, что там реализовано. у тебя там телефонный справочник, а что он реализован с помощью списка -- это уже детали реализации

2018-11-02 08:37 UTC, jzuken requested changes

2018-11-02 08:37 UTC, jzuken commented on sem1/homework4/task2/phoneBook.cpp
> +#include <iostream>
так ты вместо того, чтобы переименовать файл, просто новый добавил. используй команду git mv

2018-11-02 08:37 UTC, jzuken commented on sem1/homework4/task2/main.cpp
> +        if (newRequest == 0)
тогда уж лучше использовать switch

2018-11-06 13:25 UTC, jzuken requested changes

2018-11-06 13:25 UTC, jzuken commented on sem1/homework4/task2/phoneBook.cpp
> +    ifstream fin("phoneBook.txt");
нехорошо хардкодить имя, да ещё и в двух местах. передавай параметром из main или константу сделай

2018-11-06 13:25 UTC, jzuken commented on sem1/homework4/task2/main.cpp
> +    List *list = createList();
а чего он List, а не какой-нибудь PhoneBook?

2018-11-06 13:25 UTC, jzuken commented on sem1/homework4/task2/phoneBook.cpp
> +    long minLength = min(strlen(a), strlen(b));
phoneBook.cpp:66:34: error: ‘strlen’ was not declared in this scope

2018-11-17 06:45 UTC, merged