Task3 from homework4
foiki/spbu-Homeworks pull request #7
Opened 2018-10-17 19:42 UTC by foiki

2018-10-27 22:18 UTC, jzuken requested changes

2018-10-27 22:18 UTC, jzuken commented on sem1/homework4/task3/main.cpp
> +        long length = strlen(newLine);
а ты string.h не подключил, чтобы strlen использовать

2018-10-27 22:18 UTC, jzuken commented on sem1/homework4/task3/main.cpp
> +                ++notEmptyLines;
ты не то считаешь, что в условии требуется

2018-10-27 22:18 UTC, foiki commented on sem1/homework4/task3/main.cpp
> +        long length = strlen(newLine);
@jzuken странно, работает и без этой библиотеки

2018-11-02 12:38 UTC, jzuken commented on sem1/homework4/task3/main.cpp
> +        long length = strlen(newLine);
с моей стандартной библиотекой оно не компилируется иначе

2018-11-02 12:39 UTC, merged